name: Organize LeetCode Solutions

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show uploaded folders
        run: |
          echo "LeetHub uploaded:"
          ls -R
